name: Terraform

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Terraform action'
        required: true
        default: 'plan'
        type: choice
        options:
        - plan
        - apply
        - destroy

jobs:
  terraform:
    name: Terraform
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3

    - name: Terraform Init
      run: terraform init

    - name: Terraform Action
      run: |
        if [ "${{ github.event.inputs.action }}" == "plan" ]; then
          terraform plan
        elif [ "${{ github.event.inputs.action }}" == "apply" ]; then
          terraform apply -auto-approve
        elif [ "${{ github.event.inputs.action }}" == "destroy" ]; then
          terraform destroy -auto-approve
        fi
